Add problem CRUD API
leoleoasd/EduOJBackend pull request #34
Opened 2020-09-04 01:51 UTC by suntt2019

#18

2020-09-04 02:11 UTC, leoleoasd requested changes

2020-09-04 02:11 UTC, leoleoasd commented on app/controller/admin_problem.go
> +	problem := models.Problem{}
testcase呢

2020-09-04 02:11 UTC, leoleoasd commented on app/controller/auth.go
> +			User:  *resource.GetUserProfileForMe(&user),
直接用admin就得了吧

2020-09-04 02:11 UTC, leoleoasd commented on app/request/admin_problem.go
> +	Score     uint `json:"score" form:"score" query:"score"` // 0 for 平均分配
validate?

2020-09-04 02:11 UTC, leoleoasd commented on app/request/admin_problem.go
> +	LanguageAllowed    string `json:"language_allowed" form:"language_allowed" query:"language_allowed" validate:"required,max=255"` // E.g.    cpp,c,java,python
validate?

2020-09-04 08:38 UTC, leoleoasd commented
test

2020-09-04 08:39 UTC, leoleoasd commented on app/request/admin_problem.go
> +	Score uint `json:"score" form:"score" query:"score"` // 0 for 平均分配
@suntt2019

2020-09-04 08:39 UTC, leoleoasd commented on app/request/admin_problem.go
>  	InputFileName  string `json:"input_file_name" form:"input_file_name" query:"input_file_name" validate:"required,max=255"`
test

2020-09-09 13:18 UTC, leoleoasd requested changes

2020-09-09 13:18 UTC, leoleoasd commented on app/request/admin_problem.go
> +	Public  *bool `json:"public" form:"public" query:"public"`
required

2020-09-09 13:18 UTC, leoleoasd commented on app/request/admin_problem.go
> +	Public  *bool `json:"public" form:"public" query:"public"`
required

2020-09-09 13:18 UTC, leoleoasd commented on app/controller/admin_problem_test.go
> +				test.expectedProblem.ID = databaseProblem.ID
加个注释, ignore other fields

2020-09-09 13:18 UTC, leoleoasd commented on app/response/resource/problem.go
> +	LanguageAllowed    string `json:"language_allowed"`    // E.g.    cpp,c,java,python
直接改成数组吧
convert的时候split一下

2020-09-09 13:18 UTC, leoleoasd commented on app/controller/images_test.go
> +		_, err := base.Storage.PutObject("images", "test_image_path", &imageBuffer, int64(imageBuffer.Len()), minio.PutObjectOptions{
为啥删掉上面?

2020-09-09 13:18 UTC, leoleoasd commented on app/response/resource/problem.go
> +	Public             bool   `json:"public"`
用户看不到publicity和privacy

2020-09-09 13:18 UTC, leoleoasd commented on app/response/resource/problem.go
> +	CompileEnvironment string `json:"compile_environment"` // E.g.  O2=false
这也看不到

2020-09-09 13:18 UTC, leoleoasd commented on base/utils/query_helper_test.go
> +func getUrlStringPointer(rawUrl string, paras map[string]string) *string {
参数不能直接是url.URL吗?
我看你都是用一个url的string方法传进来, 然后再parse回去

2020-09-09 13:18 UTC, leoleoasd commented on base/validator/translations/zh/zh.go
> +	"CompareScriptID":    "比较脚本编号",
少个OldPassword和NewPassword

2020-09-09 13:18 UTC, leoleoasd commented on permission.go
> +			log.Fatal("Editing permission failed.")
Edit

2020-09-09 13:19 UTC, leoleoasd commented
@suntt2019 reviewed

2020-09-10 09:43 UTC, suntt2019 commented on app/controller/admin_problem.go
> +	problem, err := findProblem(c.Param("id"), false)
emmmm...怎么个挪位置，每太听懂[捂脸]😂

2020-10-08 08:46 UTC, leoleoasd commented on app/controller/admin_problem.go
> +	problem, err := utils.FindProblem(c.Param("id"), false)
Problem只能软删除

2020-10-08 08:55 UTC, leoleoasd commented on app/controller/admin_problem.go
> +		if err := base.Storage.RemoveObject("problems", fmt.Sprintf("%d/input/%s", problem.ID, testCase.InputFileName)); err != nil {
直接put object 就覆盖了.

2020-10-08 09:05 UTC, leoleoasd requested changes

2020-10-08 09:05 UTC, leoleoasd commented on app/controller/problem_test.go
> +		Name:               "test_get_problem_private",
1. 控制题目是否公开的field是public
2. 要显示的写出 public: false

2020-10-08 09:05 UTC, leoleoasd commented on app/controller/problem_test.go
> +				user := createUserForTest(t, "get_problem", i)
这种地方, 对于用户本身没有进行写操作, (只是创建了一个role), 其实都可以用同一个用户

2020-10-08 09:05 UTC, leoleoasd commented on base/utils/storage.go
> +func MustCreateBucket(name string) {
用 sync.Map 建一个缓存, 保证程序每次运行期间, 对于每个name , 只调用一次Exists.

2020-10-08 09:05 UTC, leoleoasd commented on base/utils/storage.go
> +func MustCreateBucket(name string) {
之后可能有创建名字是动态的bucket的需求
比如给每个problem set 创建一个bucket

2020-10-08 09:05 UTC, leoleoasd commented on base/utils/storage.go
> +func MustCreateBucket(name string) {
所以不能从程序里保证程序运行期间这个函数只被调用一次.

2021-01-18 12:21 UTC, leoleoasd requested changes

2021-01-18 12:21 UTC, leoleoasd commented on app/controller/admin_problem.go
> +	// TODO: merge this with GetProblem.
do this todo

2021-01-18 12:21 UTC, leoleoasd commented on app/controller/admin_user_test.go
> +	thisURL, err := url.ParseRequestURI(base.Echo.Reverse(name))
Reverse 的时候的参数呢?
比如/problem/:id

2021-01-21 17:20 UTC, leoleoasd approved these changes
👍

2021-01-21 17:23 UTC, merged