submission API
leoleoasd/EduOJBackend pull request #50
Opened 2021-01-27 09:00 UTC by suntt2019

closes #46

2021-01-28 11:54 UTC, leoleoasd requested changes

2021-01-28 11:54 UTC, leoleoasd commented on app/request/submission.go
> +	ProblemSetId *int   `sql:"index" gorm:"nullable" json:"problem_set_id"`
所有有关 problem set 的都应该在 problem set api 地下
所以这里只能提交 problem set id 为 0 的

2021-01-28 11:54 UTC, leoleoasd commented on app/request/submission.go
> +	OrderBy string `json:"order_by" form:"order_by" query:"order_by"`
只允许 id 倒序

2021-01-28 11:54 UTC, leoleoasd commented on app/request/submission.go
> +
只能按照题目 id 和用户 id 筛选

2021-01-28 11:54 UTC, leoleoasd commented on app/request/submission.go
> +	ProblemID uint `sql:"index" json:"problem_id"`
validation required

2021-01-28 11:54 UTC, leoleoasd commented on app/request/submission.go
> +	Language     string `json:"language"`
required

2021-01-28 11:54 UTC, leoleoasd commented on app/response/resource/submission.go
> +	ProblemSetId sql.NullInt32 `sql:"index" json:"problem_set_id"`
不需要 sql tag
以及不能用 sql.NullInt32, 换成 int*吧

2021-01-28 11:54 UTC, leoleoasd commented on app/response/submission.go
> +type CreateSubmissionResponseForAdmin struct {
为什么管理员的 response 不一样???

2021-01-28 11:54 UTC, leoleoasd commented on app/response/resource/submission.go
> +	CompilerOutputUrl string `json:"compiler_output_url"`
有单独的获取 url 的接口, 不应该在这里返回 url?

2021-01-28 11:54 UTC, leoleoasd commented on app/response/resource/submission.go
> +type SubmissionForAdmin struct {
感觉叫 detaile 更合适?毕竟用户也能看到自己的

2021-01-28 11:54 UTC, leoleoasd commented on app/response/submission.go
> +type GetSubmissionResponseForAdmin struct {
detail?

2021-01-28 11:54 UTC, leoleoasd commented on app/routes.go
> +	admin.POST("/submission", controller.Todo, middleware.HasPermission(middleware.CustomPermission{F: func(c echo.Context) bool {
路径还是改成 /problem/:pId/submission 吧
这样后面查权限的代码也简单一点

以及, 这个函数应该放在 middleware 包里面?

2021-01-28 11:54 UTC, leoleoasd commented on app/routes.go
> +		c.Set("find_problem_error", err)
为什么要存着 err?

2021-01-28 11:54 UTC, leoleoasd commented on base/utils/query_helper.go
> +			panic(errors.Wrap(err, "could not query problem"))
为什么是 panic 而不是 return?

2021-01-28 11:54 UTC, leoleoasd commented on base/utils/query_helper.go
> +			panic(errors.Wrap(err, "could not query problem"))
上面 findproblem 好像也是 panic, 一起改了?

2021-01-28 11:54 UTC, leoleoasd commented on database/migrate.go
> +					Username string `gorm:"uniqueIndex;size:30" json:"username" validate:"required,max=30,min=5"`
只需要有 id 即可, 别的 field 可删掉

2021-01-28 11:54 UTC, leoleoasd commented on database/migrate.go
> +					Username string `gorm:"uniqueIndex;size:30" json:"username" validate:"required,max=30,min=5"`
只需要有外键依赖的列即可, 比如 run 用 user 的 id, 就只需要有 id

2021-01-28 13:39 UTC, leoleoasd commented on app/request/submission.go
> +	ProblemSetId *int   `sql:"index" gorm:"nullable" json:"problem_set_id"`
去掉 nullable, 0 代表不在 set 里

2021-01-28 17:44 UTC, leoleoasd commented on app/routes.go
> +	admin.GET("/submission/:id/run/:run_id", controller.Todo).Name = "submission.getRun"
分成四个文件

2021-01-28 17:44 UTC, leoleoasd commented on database/migrate.go
> -					ProblemID uint `sql:"index" json:"problem_id" gorm:"not null"`
problemid 得留着..

2021-01-28 17:51 UTC, leoleoasd requested changes
上面写了

2021-01-29 09:05 UTC, leoleoasd reviewed
review

2021-01-30 05:13 UTC, leoleoasd requested changes

2021-01-30 05:13 UTC, leoleoasd commented on app/controller/submission.go
> +	priority := models.DEFAULT_PRIORITY
这一行为什么要放的这么靠前呢

2021-01-30 05:13 UTC, leoleoasd commented on app/controller/submission.go
> +		Language:     req.Language,
检测 language 是否在 problem 的 languageallowed 里面

2021-01-30 05:13 UTC, leoleoasd commented on app/controller/submission.go
> +		Status:       "Waiting For Judge",
Pending
status 还是在 models 那里加个文档吧
这个字段存的不是人类可读的信息, 不应该写 Waiting for judge 这样的格式...
pending / judging / accepted / wrong answer / runtime error / ...
大写 SNAKE_CASE 吧

2021-01-30 05:13 UTC, leoleoasd commented on app/controller/submission.go
> +			Sample:             true,
????

2021-01-30 05:13 UTC, leoleoasd commented on app/controller/submission_test.go
> +				expectedRS := make([]resource.Run, test.testCaseCount)
RS为啥不全程?

2021-01-30 07:05 UTC, leoleoasd approved these changes

2021-02-02 14:38 UTC, leoleoasd commented on app/controller/controller_test.go
> +	size     int64
为啥要 size?

2021-02-02 14:38 UTC, leoleoasd commented on app/controller/submission.go
> +	// TODO: save file
是 code 没存?

2021-02-02 14:38 UTC, leoleoasd commented on app/controller/submission.go
> +	// TODO: save file
还是啥意思?

2021-02-02 14:38 UTC, leoleoasd commented on app/controller/submission.go
> +		return c.JSON(http.StatusForbidden, response.ErrorResp("PERMISSION_DENIED", nil))
写一个 cover 这一行的 test?

2021-02-02 14:38 UTC, leoleoasd commented on app/controller/submission.go
> +	query := base.DB.Model(&models.Submission{}).Where("problem_set_id = ?", 0).Order("id DESC") // Force order by id desc.
可以直接把 0 写到 sql 里的

2021-02-02 14:41 UTC, suntt2019 commented on app/controller/submission.go
> +	// TODO: save file
加（在下面）完了忘记删TODO了[捂脸]

2021-02-02 14:43 UTC, suntt2019 commented on app/controller/controller_test.go
> +	size     int64
emm，之前用的时候都读两次，一次获取size，seek回去，再读一次（同时把size作为参数传进去）
后来我才想到其实创建的时候存下size不就只用读一次了😂

2021-02-02 15:33 UTC, leoleoasd commented on app/controller/submission_test.go
> +	publicFalseProblem, publicFalseProblemCreator := createProblemForTest(t, "get_submission", 0, nil)
rename to notPublicProblem?

2021-02-02 15:33 UTC, leoleoasd commented on app/controller/submission_test.go
> +				problem, user := createProblemForTest(t, "get_submission", i+2, nil)
why 2?
magic number 去掉或者加个注释吧

2021-02-02 15:53 UTC, suntt2019 commented on app/controller/submission_test.go
> +	publicFalseProblem, publicFalseProblemCreator := createProblemForTest(t, "get_submission", 0, nil)
ok，不过之前一直这么叫的[捂脸]

2021-02-02 16:08 UTC, leoleoasd approved these changes

2021-02-05 12:19 UTC, suntt2019 commented on readme.md
> +| creator |  N/A   |    all     |
刚想起来`creator`好像改成`problem_creator`了，然后target是`problem`这样？

2021-02-05 15:23 UTC, merged