Develop Class
leoleoasd/EduOJBackend pull request #65
Opened 2021-02-22 14:38 UTC by suntt2019

closes #63

2021-02-23 08:27 UTC, leoleoasd commented on app/request/class.go
> +type GetMyClassesRequest struct {
数量不会很多，就不分页了吧？

2021-02-23 08:28 UTC, leoleoasd commented on app/request/class.go
> +type GetMyClassesRequest struct {
api可以不改，吧默认的limit改大一点就好

2021-02-25 13:15 UTC, leoleoasd requested changes

2021-02-25 13:15 UTC, leoleoasd commented on app/controller/class.go
> +		panic(errors.Wrap(err, "could not find class managing"))
这个是获取class列表吧，是不是不用带着user？

2021-02-25 13:15 UTC, leoleoasd commented on app/controller/class.go
> +	if err := base.DB.Model(&user).Preload("Managers").Preload("Students").Association("ClassesTaking").Find(&classes); err != nil {
这个是获取class列表吧，是不是不用带着user？

2021-02-25 13:15 UTC, leoleoasd commented on app/controller/class.go
> +	utils.PanicIfDBError(base.DB.Select("invite_code").Find(&classes), "could not find classes for generating invite codes")
？？？？？？？？？？？？？？

2021-02-25 13:15 UTC, leoleoasd commented on app/controller/class.go
> +	utils.PanicIfDBError(base.DB.Select("invite_code").Find(&classes), "could not find classes for generating invite codes")
每次生成一个，查是否存在，不存在就返回
如果有几千个班级，你都查询后O(n)遍历吗？？？？

2021-02-25 13:15 UTC, leoleoasd commented on app/controller/class.go
> +			if c.InviteCode == code {
怎么这么喜欢O(n)遍历？？？

2021-02-25 13:15 UTC, leoleoasd commented on base/utils/utils.go
> +func IdUniqueInA(a []uint, b []uint) (uniqueA []uint) {
叫 集合的减运算 是不是更合适？
"InA"看上去很让人迷惑

2021-02-25 13:15 UTC, leoleoasd commented on database/models/class.go
> +	if err := base.DB.Find(&users, ids).Error; err != nil {
添加association这个操作理论上只会用到user id
如果构造一个只有id的user数组，传入association.append，试试能正常工作吗？

2021-02-25 13:15 UTC, leoleoasd commented on database/models/class.go
> +	if err := base.DB.Find(&users, ids).Error; err != nil {
同add

2021-02-25 14:00 UTC, suntt2019 commented on database/models/class.go
> +	if err := base.DB.Find(&users, ids).Error; err != nil {
emmm，我这里试好像不行

2021-02-25 14:43 UTC, leoleoasd requested changes

2021-02-25 14:43 UTC, leoleoasd commented on app/controller/class.go
> +	for crashed {
直接count != 0不就得了？？？

2021-02-25 14:43 UTC, leoleoasd commented on app/controller/class.go
> +	for crashed {
以及这个函数为啥public

2021-02-27 12:22 UTC, merged